trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo "hello world"
  displayName: 'hello'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'coverage/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
